#!/usr/bin/env kotlin

import java.io.File
import java.time.LocalDateTime

val regularList: Array<File>? = File("../../../uikitMain/src/commonMain/kotlin/com/millentec/compose/uikit/icons/fluenticons/regular/dp20").listFiles {
    it.isFile && it.extension == "kt"
}
var regularString: String = ""
regularList?.forEach {
    if ("fun FluentIcons." in it.readText()) {
        val str = "FluentIcons.${it.nameWithoutExtension.replaceFirstChar { char ->
            if (char.isUpperCase()) char.lowercaseChar() else char
        }}(primaryColor, layered),"
        println(str)
        regularString += "        $str\n"
    } else {
        val str = "FluentIcons.${it.nameWithoutExtension},"
        regularString += "        $str\n"
    }
}

println()

val filledList: Array<File>? = File("../../../uikitMain/src/commonMain/kotlin/com/millentec/compose/uikit/icons/fluenticons/filled/dp20").listFiles {
    it.isFile && it.extension == "kt"
}
var filledString: String = ""
filledList?.forEach {
    if ("fun FluentIcons.Filled" in it.readText()) {
        val str = "FluentIcons.Filled.${it.nameWithoutExtension.replaceFirstChar { char ->
            if (char.isUpperCase()) char.lowercaseChar() else char
        }}(primaryColor, layered),"
        println(str)
        filledString += "        $str\n"
    } else {
        val str = "FluentIcons.Filled.${it.nameWithoutExtension},"
        filledString += "        $str\n"
    }
}

val builtString = """
/*
 * Generated by Kotlin Script.
 * Generation time: ${LocalDateTime.now()}
 */
 
package com.millentec.compose.uikit
    
import com.millentec.compose.uikit.icons.fluenticons.*
import com.millentec.compose.uikit.icons.fluenticons.regular.dp20.*
import com.millentec.compose.uikit.icons.fluenticons.filled.dp20.*
import androidx.compose.ui.graphics.Color

class IconGalleryList(
    primaryColor: Color,
    layered: Boolean,
) {
    val regularIconsList = listOf(
$regularString
    )
    
    val filledIconsList = listOf(
$filledString
    )
}
""".trimIndent()

val saveFile = File("../commonMain/kotlin/com/millentec/compose/uikit/IconGalleryList.g.kt")
if (!saveFile.exists()) {
    saveFile.createNewFile()
}
saveFile.writeText(builtString)