#!/usr/bin/env kotlin

import java.io.File
import java.time.LocalDateTime

val regularList: Array<File>? = File("../../../uikitMain/src/commonMain/kotlin/com/millentec/compose/uikit/symbols/uikitsymbols/regular/dp20").listFiles {
    it.isFile && it.extension == "kt"
}
var regularString: String = ""
regularList?.forEach {
    if ("fun UIKitSymbols." in it.readText()) {
        val str = "UIKitSymbols.${it.nameWithoutExtension.replaceFirstChar { char ->
            if (char.isUpperCase()) char.lowercaseChar() else char
        }}(primaryColor, layered),"
        println(str)
        regularString += "        $str\n"
    } else {
        val str = "UIKitSymbols.${it.nameWithoutExtension},"
        println(str)
        regularString += "        $str\n"
    }
}

println()

val filledList: Array<File>? = File("../../../uikitMain/src/commonMain/kotlin/com/millentec/compose/uikit/symbols/uikitsymbols/filled/dp20").listFiles {
    it.isFile && it.extension == "kt"
}
var filledString: String = ""
filledList?.forEach {
    if ("fun UIKitSymbols.Filled" in it.readText()) {
        val str = "UIKitSymbols.Filled.${it.nameWithoutExtension.replaceFirstChar { char ->
            if (char.isUpperCase()) char.lowercaseChar() else char
        }}(primaryColor, layered),"
        println(str)
        filledString += "        $str\n"
    } else {
        val str = "UIKitSymbols.Filled.${it.nameWithoutExtension},"
        println(str)
        filledString += "        $str\n"
    }
}

val builtString = """
/*
 * Generated by Kotlin Script.
 * Generation time: ${LocalDateTime.now()}
 */
 
package com.millentec.compose.uikit
    
import com.millentec.compose.uikit.symbols.uikitsymbols.*
import com.millentec.compose.uikit.symbols.uikitsymbols.regular.dp20.*
import com.millentec.compose.uikit.symbols.uikitsymbols.filled.dp20.*
import androidx.compose.ui.graphics.Color

class IconGalleryList(
    primaryColor: Color,
    layered: Boolean,
) {
    val regularIconsList = listOf(
$regularString
    )
    
    val filledIconsList = listOf(
$filledString
    )
}
""".trimIndent()

val saveFile = File("../commonMain/kotlin/com/millentec/compose/uikit/IconGalleryList.g.kt")
if (!saveFile.exists()) {
    saveFile.createNewFile()
}
saveFile.writeText(builtString)