/*
 * Generated by Kotlin Script.
 * Generation time: 2026-07-19T21:08:40.157986200
 */
 
package com.millentec.compose.uikit
    
import androidx.compose.ui.graphics.Color
import com.millentec.compose.uikit.icons.fluenticons.FluentIcons
import com.millentec.compose.uikit.icons.fluenticons.filled.dp20.*
import com.millentec.compose.uikit.icons.fluenticons.regular.dp20.*

class IconGalleryList(
    primaryColor: Color,
    layered: Boolean,
) {
    val regularIconsList = listOf(
        FluentIcons.Add,
        FluentIcons.addCircle(primaryColor, layered),
        FluentIcons.Apps,
        FluentIcons.Bluetooth,
        FluentIcons.bluetoothDisabled(primaryColor, layered),
        FluentIcons.Bug,
        FluentIcons.Checkmark,
        FluentIcons.ChevronArrowDown,
        FluentIcons.ChevronArrowLeft,
        FluentIcons.ChevronArrowRight,
        FluentIcons.ChevronArrowUp,
        FluentIcons.designIdeas(primaryColor, layered),
        FluentIcons.Dismiss,
        FluentIcons.Document,
        FluentIcons.documentSearch(primaryColor, layered),
        FluentIcons.GameController,
        FluentIcons.gameControllerError(primaryColor, layered),
        FluentIcons.Home,
        FluentIcons.layerDiagonal(primaryColor, layered),
        FluentIcons.layerDiagonalSparkle(primaryColor, layered),
        FluentIcons.Navigation,
        FluentIcons.options(primaryColor, layered),
        FluentIcons.Resize,
        FluentIcons.Settings,
        FluentIcons.shapes(primaryColor, layered),
        FluentIcons.Symbols,
        FluentIcons.Tag,
        FluentIcons.toggleMultiple(primaryColor, layered),
        FluentIcons.Tools,
        FluentIcons.wand(primaryColor, layered),
        FluentIcons.warning(primaryColor, layered),
        FluentIcons.Wheelchair,
        FluentIcons.wifi(primaryColor, layered),
        FluentIcons.wifiOff(primaryColor, layered),
        FluentIcons.Wrench,
        FluentIcons.ZoomFit,
        FluentIcons.ZoomIn,
        FluentIcons.ZoomOut,

    )
    
    val filledIconsList = listOf(
        FluentIcons.Filled.Add,
        FluentIcons.Filled.AddCircle,
        FluentIcons.Filled.Bluetooth,
        FluentIcons.Filled.bluetoothDisabled(primaryColor, layered),
        FluentIcons.Filled.Bug,
        FluentIcons.Filled.Checkmark,
        FluentIcons.Filled.ChevronArrowDown,
        FluentIcons.Filled.ChevronArrowLeft,
        FluentIcons.Filled.ChevronArrowRight,
        FluentIcons.Filled.ChevronArrowUp,
        FluentIcons.Filled.designIdeas(primaryColor, layered),
        FluentIcons.Filled.Dismiss,
        FluentIcons.Filled.Document,
        FluentIcons.Filled.documentSearch(primaryColor, layered),
        FluentIcons.Filled.GameController,
        FluentIcons.Filled.gameControllerError(primaryColor, layered),
        FluentIcons.Filled.Home,
        FluentIcons.Filled.layerDiagonal(primaryColor, layered),
        FluentIcons.Filled.layerDiagonalSparkle(primaryColor, layered),
        FluentIcons.Filled.Navigation,
        FluentIcons.Filled.Resize,
        FluentIcons.Filled.Settings,
        FluentIcons.Filled.shapes(primaryColor, layered),
        FluentIcons.Filled.Symbols,
        FluentIcons.Filled.Tag,
        FluentIcons.Filled.toggleMultiple(primaryColor, layered),
        FluentIcons.Filled.Tools,
        FluentIcons.Filled.wand(primaryColor, layered),
        FluentIcons.Filled.Warning,
        FluentIcons.Filled.Wheelchair,
        FluentIcons.Filled.wifi(primaryColor, layered),
        FluentIcons.Filled.wifiOff(primaryColor, layered),
        FluentIcons.Filled.Wrench,
        FluentIcons.Filled.ZoomFit,
        FluentIcons.Filled.ZoomIn,
        FluentIcons.Filled.ZoomOut,

    )
}